CU-862jk516x - Card Component. The task is completed
andrewmarushko/skyapp-client pull request #29
Opened 2023-04-11 12:17 UTC by OleksandrMykhailovskyi

Here are the parts of functional, that have been done in the PR: 

- Configured Card component and its styles. (div and children inside)
- Added hover, focus and focus-within effects.
- Styles for the dark theme.
- Added the temporary grids on the page where the Card components are used.

2023-04-11 12:17 UTC, andrewmarushko commented
Task linked: [CU-862jk516x Card Component](https://app.clickup.com/t/862jk516x)

2023-04-11 12:31 UTC, andrewmarushko requested changes

2023-04-11 12:31 UTC, andrewmarushko commented on tailwind.config.js
> +        customMd: 'var(--shadow-medium)',
Сделай более глобальное название кастом не подходит

2023-04-11 12:52 UTC, OleksandrMykhailovskyi commented on tailwind.config.js
> +        customMd: 'var(--shadow-medium)',
а если перебить дефолтные значения у ключей sm и md?

2023-04-13 18:08 UTC, andrewmarushko commented on styles/globals.css
> +  --accents-0: #000;
It's should be default or accent 
Don't use 0

2023-04-13 18:08 UTC, andrewmarushko commented on styles/globals.css
> +  } */
Delete it if not needed

2023-04-13 18:09 UTC, andrewmarushko commented on tailwind.config.js
> +          DEFAULT: 'var(--accents-0)',
So if u use like that just leave accent

2023-04-13 18:10 UTC, andrewmarushko commented on yarn.lock
> +"@fullhuman/postcss-purgecss@^2.1.2":
Also update lock file after changing next version

2023-04-13 18:22 UTC, OleksandrMykhailovskyi commented on package.json
> +    "next": "13.3.1-canary.4",
but we arranged, that we will try this version of next. "next": "^13.3.0 Does not work in Windows :(

2023-04-13 18:41 UTC, andrewmarushko approved these changes

2023-04-13 18:41 UTC, merged