Header cu 862jm1wvp
andrewmarushko/skyapp-client pull request #50
Opened 2023-04-19 23:38 UTC by OleksandrMykhailovskyi

Added the following functional here: 

- Burger menu behavior for smaller screens.
- Rearranged the header elements structure.
- Added new variants of Links.
- Added the styles both for light and dark themes.

2023-04-20 01:49 UTC, andrewmarushko approved these changes
@OleksandrMykhailovskyi Check my minor fix commit
https://github.com/andrewmarushko/skyapp-client/pull/50/commits/81fb27aa3e7b6336765dad511971705ce9d38719

2023-04-20 01:57 UTC, andrewmarushko requested changes

2023-04-20 01:57 UTC, andrewmarushko commented on components/footer.tsx
> +import { ModeToggle } from './mode-toggle';
use relative path

2023-04-20 01:57 UTC, andrewmarushko commented on components/footer.tsx
> +import { buttonVariants } from './ui/button';
Here too `@/component/ui/button`

2023-04-20 01:57 UTC, andrewmarushko commented on components/ui/burger-menu.tsx
> +  };
Мне кажется что если ты откроешь меню и и не закроешь то Стейт будет иметь старое значение 
`(prev) => !prev`

а вообще сделай хук для этого поведения, он еще может понадобиться например на кнопке фидбэк и модалке

2023-04-20 01:57 UTC, andrewmarushko commented on styles/globals.css
> +  --geist-link-radius: 9999px;
lool юзай 100%

2023-04-20 03:47 UTC, andrewmarushko commented
Task linked: [CU-862jm1wvp Header](https://app.clickup.com/t/862jm1wvp)

2023-04-20 11:50 UTC, OleksandrMykhailovskyi commented on components/ui/button.tsx
> -          "w-6 h-10 flex justify-center items-center rounded bg-transparent border-none transition-background-color duration-200 ease select-none"
а почему тут удалил эти стили?. Они используются для бургер-меню кнопки

2023-04-20 13:13 UTC, OleksandrMykhailovskyi commented on components/ui/burger-menu.tsx
> +  };
то есть нужно сделать так, чтоб когда я открыл бургер меню, оно открылось. Потом я перешел на экран, где этот блок скрыт, то isOpen должно становиться false. И по возвращении на мобильную версию - блок должен быть скрытым. А не как сейчас, что при возвращении на мобильную версию - isOpen равно true и nav открыт ?

2023-04-20 13:54 UTC, OleksandrMykhailovskyi commented on components/ui/burger-menu.tsx
> +  };
в общем реализовал такую штуку, чтоб когда навигация была открыта на мобиле и юзер решил перейти на большее расширение экрана, а потом вернуться назад, навигация автоматически закрывалась. И подкорректировал setIsOpen . И вынес toggleBurgerMenu функцию из бургерМеню в Хедер. Щас буду делать отдельный хук.

  const toggleBurgerMenu = () => {
    setIsOpen((prev) => !prev);
  };

![image](https://user-images.githubusercontent.com/39292493/233387825-0926632a-44f5-454b-9097-73fe53729ad8.png)

2023-04-25 13:26 UTC, andrewmarushko approved these changes

2023-04-25 13:27 UTC, merged