Navigation component cu 862jmeg08
andrewmarushko/skyapp-client pull request #51
Opened 2023-04-21 15:02 UTC by OleksandrMykhailovskyi

Here is the functional added to the PR: 

- Created mobile-nav component that is used in header.
- There are the animations and open/close effects there. Also, if the screen resolution changes from desktop to mobile and back, the elements are automatically closed.
- There is the typization for navigationData data.
- Created a custom Li component with CVA. It is used in mobile-nav component, inside our NavigationLink. This the way, how the HTML tags take place on vercel.com.
- Also, the real data is added to the mobile menu, except the buttons group, that does not have back realization yet.
- Checked all the imports for them to be generic ones.
- There are the styles for both light and dark themes.

2023-04-21 15:02 UTC, andrewmarushko commented
Task linked: [CU-862jm1wvp Header](https://app.clickup.com/t/862jm1wvp)

2023-04-21 15:02 UTC, andrewmarushko commented
Task linked: [CU-862jmeg08 Navigation Component](https://app.clickup.com/t/862jmeg08)

2023-04-21 23:13 UTC, andrewmarushko requested changes

2023-04-21 23:13 UTC, andrewmarushko commented on components/ui/li.tsx
> +          'text-accent-400 dark:text-accent-500',
используй menu and submenu нейминг вроде как болеее логично

2023-04-24 07:42 UTC, OleksandrMykhailovskyi commented on components/mobile-nav.tsx
> +          <h3 className='font-medium text-base -tracking-widest leading-6'>
на верселе как раз так было, брал оттуда структуру HTML

![image](https://user-images.githubusercontent.com/39292493/233930899-a216dcd4-c4d4-4334-8198-51efacf124df.png)

2023-04-24 09:55 UTC, OleksandrMykhailovskyi commented on components/mobile-nav.tsx
> +          <h3 className='font-medium text-base -tracking-widest leading-6'>
заюзал Аккордеон

2023-04-24 16:03 UTC, andrewmarushko approved these changes

2023-04-24 16:03 UTC, merged