CU-862jqw35r - Tailwind config. Modified global.css and tailwind.config files
andrewmarushko/skyapp-client pull request #77
Opened 2023-05-03 01:25 UTC by OleksandrMykhailovskyi

Here is the PR with the changes in global.css and tailwind.config files. It will be required to change the styles in the components then.

- I have removed the duplicated classes.
- Refactored their names.
- Removed unused classes.
- Also, rems are used instead of pixels now.

Please check whether this structure looks nice and what can be also impoved. 

Also, I have tried using the approach from use-themes https://www.npmjs.com/package/next-themes with the colors configuration for the dark mode. Hovewer, the styles set up for the dark theme, did not work. It seems, this approach does not work with Tailwind.

`[data-theme='dark'] {
  --background: black;
  --foreground: white;
}`

2023-05-03 08:55 UTC, andrewmarushko requested changes
Проанализирай весь проект приблезительно по цветам
https://vercel.com/design/color

тут не так много цветов которые мы можем использовать, ошибка была в том что ты начал под копирку копировать, чего делать не надо было.


Алгоритм такой, посмотреть средние все значения для бордеров Спейсов и так далее и использовать у нас приближенное значение из дефолтного тейлвинда.


Кастомные штуки по типу Hero - где шрифт большей мы можем расширить тему, для него это ок. но делать еще 100500 размеров которые нам по сути то и не нужны нет смысла, тогда просто пропадает смысл использование tailwinds. из коробки он уже предлагает очень большой набор, где нужно перебить всего несколько значений по типу может теней, цветов и добавить пару значений кастомных для узких мест

2023-05-03 08:55 UTC, andrewmarushko commented on styles/globals.css
> +  --geist-experimental-color-gray-9: var(--accents-4);
Если мы тут используем accents нужна ли нам эта переменная и вообще эти все цвета, если мы будем использовать 2-3 серых цвета, есть смысл или добавить их в accent палитру или использовать очень приближенный цвет из нашей палитры

2023-05-03 08:55 UTC, andrewmarushko commented on styles/globals.css
>    --geist-experimental-color-gray-a10: rgba(0,0,0,.91);
Тоже самое здесь, зачем нам цвета которые всеголишь оттенок тесного и 10 штук, для чего нужно столько цветов.

2023-05-03 08:55 UTC, andrewmarushko commented on styles/globals.css
>    --shadow-hover-dark: 0 0 0 1px var(--geist-foreground);
Тут тоже используй в коде accent-2 и фореграунд например и эти 2 переменные уйдут, они не нужны

2023-05-03 08:55 UTC, andrewmarushko commented on styles/globals.css
>    --button-custom-fg: var(--accents-9);
и тут, это не custom-fg если он использует цвет из палитры

2023-05-03 21:14 UTC, OleksandrMykhailovskyi commented on styles/globals.css
>    --geist-experimental-color-gray-a10: rgba(0,0,0,.91);
удалил вообще это все

2023-05-03 21:15 UTC, OleksandrMykhailovskyi commented on styles/globals.css
> +  --geist-experimental-color-gray-9: var(--accents-4);
взял просто цвета из секции primary https://vercel.com/design/color#primary , остальные серые удалил. Думаю должно их хватить

2023-05-03 22:20 UTC, andrewmarushko requested changes

2023-05-03 22:20 UTC, andrewmarushko commented on styles/globals.css
>    --max-width-100vw: 100vw;
юзать 100% блока

2023-05-03 22:20 UTC, andrewmarushko commented on styles/globals.css
> +  --min-width-custom-41x: 10.25rem;
можем обойтись без этого и ставить ширину `w-40` например что равно 10rem

2023-05-03 22:20 UTC, andrewmarushko commented on styles/globals.css
>    --height-60vh: 60vh;
это тоже можем удалить 
`h-16` и для чего нам высота в 60vh????

2023-05-03 22:20 UTC, andrewmarushko commented on styles/globals.css
>    --backdrop-saturate-180: 1.8;
backdrop-saturate-100 это 1.5 добавь 180 например что бы не перебивать дефолтное значение

2023-05-03 22:20 UTC, andrewmarushko commented on styles/globals.css
> +  --line-height-18x-half: 4.625rem;
тут тоже можем использовать приближенное дефолтное значение но text-6xl уже идет со значением line-height

2023-05-03 22:20 UTC, andrewmarushko commented on styles/globals.css
> +  --transition-timing-function-default-ease: cubic-bezier(0.25, 0.1, 0.25, 1.0);
удали финкшин и дефаулт

2023-05-03 22:20 UTC, andrewmarushko commented on tailwind.config.js
> +        '4rem': 'var(--font-size-4rem)',
хоровое название

2023-05-03 22:20 UTC, andrewmarushko commented on tailwind.config.js
> +        14: 'var(--line-height-14)',
и тут

2023-05-03 22:20 UTC, andrewmarushko commented on tailwind.config.js
>          '60vh': 'var(--height-60vh)',
это нам зачем?
для этого если оно нужно можно создать отдельный класс а не держать в конфиге только для одного рейса

2023-05-03 22:20 UTC, andrewmarushko commented on tailwind.config.js
> +        'custom-sm-dark': 'var(--shadow-small-dark)',
если мы будем использовать только эти значения можно перебить текущие в тел винде и назвать по нормальному

2023-05-03 22:20 UTC, andrewmarushko commented on tailwind.config.js
> +        'custom-10.25rem': "var(--min-width-custom-41x)"
не называй так поменяй или мы это уже удалить должны

2023-05-03 22:20 UTC, andrewmarushko commented on tailwind.config.js
> +        1: 'var(--z-index-1)',
зачем нам это?

2023-05-04 09:12 UTC, andrewmarushko commented on styles/globals.css
>    --backdrop-saturate-180: 1.8;
проехали не досмотрел )))

2023-05-04 09:42 UTC, OleksandrMykhailovskyi commented on tailwind.config.js
>          '60vh': 'var(--height-60vh)',
пока буду юзать обычный height

2023-05-04 10:27 UTC, andrewmarushko commented
Task linked: [CU-862jqn982 Refactoring existing codebase](https://app.clickup.com/t/862jqn982)

2023-05-04 10:27 UTC, andrewmarushko commented
Task linked: [CU-862jqw35r Tailwind config](https://app.clickup.com/t/862jqw35r)

2023-05-04 10:54 UTC, andrewmarushko requested changes

2023-05-04 10:54 UTC, andrewmarushko commented on styles/globals.css
> +  --shadow-none	: 0 0 #0000;
для чего нам это свойство перебивать на точно такое же по дефолту?
<img width="418" alt="Screenshot 2023-05-04 at 12 45 23" src="https://user-images.githubusercontent.com/4026421/236182678-d8b2a7df-40ec-4dbd-8fb3-7d2b0bd58497.png">

2023-05-04 10:54 UTC, andrewmarushko commented on styles/globals.css
> +  --geist-gap-x2: calc(2 * var(--geist-gap));
--geist-gap-double звучит получше

2023-05-04 10:54 UTC, andrewmarushko commented on styles/globals.css
> +  --geist-form-height: var(--geist-space-medium); */
А если форма будет большая, зачем это свойство?

2023-05-04 10:54 UTC, andrewmarushko commented on styles/globals.css
> +  --line-height-18x: 4.5rem;
удали `x`

2023-05-04 10:54 UTC, andrewmarushko commented on tailwind.config.js
> +        'header-dark': 'var(--shadow-header-dark)',
назови более обобщенно, я не понимаю что за транзишен хедер

2023-05-04 10:54 UTC, andrewmarushko commented on tailwind.config.js
>          2000: 'var(--z-index-2000)'
зачем этот дополнительный z-index?
нам от -50 до 50 не хватит?

2023-05-04 11:30 UTC, OleksandrMykhailovskyi commented on styles/globals.css
> +  --geist-gap-x2: calc(2 * var(--geist-gap));
но я закомментил это, позже удалю, как в компонентах поменяю, не буду использовать

2023-05-04 11:31 UTC, OleksandrMykhailovskyi commented on styles/globals.css
> +  --geist-form-height: var(--geist-space-medium); */
тоже закомментил, не буду использовать

2023-05-04 12:10 UTC, andrewmarushko commented
Delete plz all commented code

2023-05-04 12:10 UTC, andrewmarushko requested changes

2023-05-04 12:10 UTC, andrewmarushko commented on styles/globals.css
> +  --geist-gap-x2: calc(2 * var(--geist-gap));
???

2023-05-04 12:30 UTC, andrewmarushko approved these changes
Гуд

2023-05-04 12:35 UTC, merged