Graph ql integration cu 862jruh8t
andrewmarushko/skyapp-client pull request #84
Opened 2023-05-08 15:05 UTC by andrewmarushko

2023-05-08 15:05 UTC, andrewmarushko commented
Task linked: [CU-862jruh8t GraphQL Integration](https://app.clickup.com/t/862jruh8t)

2023-05-10 17:37 UTC, OleksandrMykhailovskyi commented on app/(indoors)/indoor/page.tsx
> +  } = await apiClient.query({ query: indoorLandingPageSeoQuery });
блин, а это удобно)

2023-05-10 18:15 UTC, OleksandrMykhailovskyi requested changes

2023-05-10 18:15 UTC, OleksandrMykhailovskyi commented on components/header.tsx
> +      className={`ease min-h-header-height sticky top-0 z-40 flex w-full max-w-full justify-center bg-transparent transition-background-color-and-box-shadow duration-200 dark:border-b-stone-700 ${
что-то похожее, как и с футером, в процессе мержа вернулись старые классы, нужно сделать, как было в этих 2 строках

2023-05-10 21:32 UTC, merged