CU-862jrtpeq - Header
andrewmarushko/skyapp-client pull request #85
Opened 2023-05-08 17:40 UTC by OleksandrMykhailovskyi

- Modified the styles for the dropdown section of the Navigation

2023-05-08 17:40 UTC, andrewmarushko commented
Task linked: [CU-862jrtpeq Header](https://app.clickup.com/t/862jrtpeq)

2023-05-08 18:17 UTC, andrewmarushko requested changes

2023-05-08 18:17 UTC, andrewmarushko commented on styles/globals.css
> +  --accent: 0 0 0;
для чего это сделал?

2023-05-08 18:56 UTC, OleksandrMykhailovskyi commented on styles/globals.css
> +  --accent: 0 0 0;
чтоб можно было опасити добавлять в классах https://tailwindcss.com/docs/customizing-colors#using-css-variables

2023-05-08 19:33 UTC, andrewmarushko commented on styles/globals.css
> +  --accent: 0 0 0;
так юзай hsl или rgba

2023-05-09 10:29 UTC, andrewmarushko approved these changes

2023-05-09 10:29 UTC, merged